### ISSUE TITLE
Incorrect name for Forge Mod/Forge + LiteLoader files

### ISSUE THREAD

**Issue by browsky300** [ImpactDevelopment/Installer#115]
**Describe the bug**
When saving several versions of the Forge mod, all of them will have the name of the first one saved.

**To Reproduce**
1. Select "Forge Mod" or "Forge + LiteLoader" from the "Install for:" dropdown menu
2. Click "Save as"
3. Close the Save menu
4. Change the Impact version in the installer to any other version
5. Click "Save as"
6. Observe that the new file's name does not match the version selected

**Expected behavior**
The name of the new file matches the Impact version selected.

**System Information**
 - OS: Windows 10
 - Installer version: 0.9.3
 - Installer format: .exe
 - Java version: 1.8.0_271-b09

**Additional context**

[Screenshot](https://gyazo.com/982a190fedb196fe1b9cb99b0b6a26d7). Note the discrepancy in the version selected and the name.

**Comment by LeafHacker** [comment]
In 0.9.4 the Save As dialog will always open with the "default" destination setting. This should fix your issue but could be confusing in a few edge-cases:

- If the installer GUI is opened with `--destination`, this will be ignored since the _default_ value is used by the dialog.
- If the user opens Save As multiple times expecting their changes to persist, they will be disappointed
    - It might be possible to make it so that they keep their changes if they exit via cancel and then re-open, but idk if this is a good idea, and would needlessly complicate the code.
